Repository openedx/frontend-app-publisher, pull requests merged in 2023-01, with the labels that each got.

#811 fix: UX issue to open link in new window as default option in TinyMCE editor
  src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
  src/components/RichEditor/index.jsx
Labels: product review, open-source-contribution

#814 fix: update DateTime field to update custom time
  src/components/DateTimeField/index.jsx
Labels: open-source-contribution

#757 refactor: upgraded frontend-build version to v12
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Collaborator/index.jsx
  src/components/Collaborator/renderSuggestion.jsx
  src/components/CourseTable/index.jsx
  src/components/CreateCoursePage/index.jsx
  src/components/CreateCourseRunPage/index.jsx
  src/components/EditCoursePage/AdditionalMetadataFields.jsx
  src/components/EditCoursePage/CollapsibleCourseRun.jsx
  src/components/EditCoursePage/CourseButtonToolbar.jsx
  src/components/EditCoursePage/CourseRunButtonToolbar.jsx
  src/components/EditCoursePage/EditCourseForm.jsx
  src/components/EditCoursePage/EditCoursePage.test.jsx
  src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
  src/components/EditCoursePage/index.jsx
  src/components/Header/Header.test.jsx
  src/components/Header/index.jsx
  src/components/ImageUpload/index.jsx
  src/components/ListField/index.jsx
  src/components/LoadingSpinner/index.jsx
  src/components/RenderSelectField/updated-paragon-component.jsx
  src/components/SidePanes/Comment.jsx
  src/components/SidePanes/CommentsPane.jsx
  src/components/SidePanes/Pane.jsx
  src/components/SidePanes/User.jsx
  src/components/SidePanes/UsersPane.jsx
  src/components/SidePanes/index.jsx
  src/components/Staffer/renderStaffSuggestion.jsx
  src/components/StafferPage/SocialLinks.jsx
  src/components/StafferPage/index.jsx
  src/components/TableComponent/index.jsx
  src/containers/CreateCourse/CreateCourse.test.jsx
  src/containers/MainApp/AppTests.test.jsx
  src/data/reducers/collaboratorInfo.js
  src/data/reducers/collaboratorOptions.js
  src/data/reducers/comments.js
  src/data/reducers/courseEditors.js
  src/data/reducers/courseInfo.js
  src/data/reducers/courseOptions.js
  src/data/reducers/courseRunOptions.js
  src/data/reducers/courseSubmitInfo.js
  src/data/reducers/courseTagOptions.js
  src/data/reducers/darkMode.js
  src/data/reducers/organizationRoles.js
  src/data/reducers/organizationUsers.js
  src/data/reducers/publisherUserInfo.js
  src/data/reducers/sourceInfo.js
  src/data/reducers/stafferInfo.js
  src/data/reducers/table.js
  src/data/services/DiscoveryDataApiService.js
Labels: engineering review
